{}

vscode:
  extensions:
    - HookyQR.beautify@1.5.0:mXo/OcopUVNHHxCPZWwlxQ==
vscode:
  extensions:
    - techer.open-in-browser@2.0.0:Qv25RdB8dvt/hv1HZBwW/g==
vscode:
  extensions:
    - vscodevim.vim@1.12.4:nIIc71K1blhNiazHIBCo+Q==
vscode:
  extensions:
    - vscodevim.vim@1.12.4:nIIc71K1blhNiazHIBCo+Q==